### ISSUE TITLE
migrate POA to cosmos/modules

### ISSUE THREAD

**Issue by hxrts** [allinbits/modules#7]
It would be great to include the POA module in the main [cosmos/modules](https://github.com/cosmos/modules) repo for better visibility once you're confident with the implementation.

**Comment by PaddyMc** [comment]
Sounds good, when the POA module get to a prod ready state, we can have the discussion :handshake:

**Comment by EduardoFromTheFuture** [comment]
What happened to the PoA module? Why was it never merged into the Cosmos SDK?
